## Customized analysis options for this workspace.
## The project previously included the full `flutter_lints` ruleset which
## produced many non-critical info/warning issues. To keep the analyzer
## useful while avoiding noise during development we apply a smaller, focused
## ruleset here and keep build/artifact folders excluded.

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - android/.gradle/**
    - ios/Pods/**
    - ios/Flutter/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    deprecated_member_use: ignore
    depend_on_referenced_packages: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
    use_super_parameters: ignore
    use_key_in_widget_constructors: ignore
    unnecessary_this: ignore
    curly_braces_in_flow_control_structures: ignore
    unnecessary_brace_in_string_interps: ignore
    avoid_relative_lib_imports: ignore
    unused_import: ignore
    unused_field: ignore
    unused_element: ignore
    prefer_final_fields: ignore
    library_prefixes: ignore
    empty_catches: ignore
    use_rethrow_when_possible: ignore

# Minimal linter ruleset - enable only a couple of helpful rules to avoid
# overwhelming developer with style/info messages. We can tighten this later.
linter:
  rules:
    avoid_print: false
    prefer_single_quotes: false
